version: "3"
services:
# Database
  DB_Services:
    build:
      context: .
      dockerfile: DB_Services/DB_Services.Dockerfile
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234
    volumes:
      - type: bind 
        source: ./DB_Services/data/db
        target: /data/db
    image: mongo:4.4.4
    ports:
      - "27017:27017"
  DB_User:
    build:
      context: .
      dockerfile: DB_User/DB_User.Dockerfile
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234
    volumes:
      - type: bind 
        source: ./DB_User/data/db
        target: /data/db
    image: mongo:4.4.4
    ports:
      - "27117:27017"
# API
  API_MBTI:
    build:
      context: .
      dockerfile: API_MBTI/API_MBTI.Dockerfile
    image: node:14.16
    ports:
      - "3000:3000"
#    depends_on:
#      - DB_Services
#      - DB_User
  API_User:
    build:
      context: .
      dockerfile: API_User/API_User.Dockerfile
    image: node:14.16
    ports:
      - "3100:3100"
#    depends_on:
#      - DB_Services
#      - DB_User